ansible-2
Otus-DevOps-2018-09/Andreyovs_infra pull request #12
Opened 2018-11-14 12:23 UTC by Andreyovs

# Выполнено ДЗ № 9

 - [ +] Основное ДЗ
 - [+ ] Задание со *

## В процессе сделано:
 Created ansible playbooks
  - `reddit_app_one_play` 
  - `reddit_app_multiple_plays`
  - `app.yml`, `db.yml`, and `deploy.yml`  The playbooks imported in `site.yml` in predefined order to deploy Reddit application.
  - `packer_db.yml` and `packer_app.yml` are the playbooks for packer images provisioning using ansible
- Changed provisioning config in `packer/app.json` and `packer/db.json` to replace bash scripts with ansible playbooks

## PR checklist
 - [+ ] Выставил label с номером домашнего задания
 - [+ ] Выставил label с темой домашнего задания

2018-12-11 20:52 UTC, ujhgj requested changes

2018-12-11 20:52 UTC, ujhgj commented on README.md
> +- Created configuration for dynamic inventory using `gce.py`
однако, в ansible.cfg у вас зафиксирован статический inventory

2018-12-11 21:00 UTC, Andreyovs commented
Так там коммент же был что не получилось. Я в следующей разобрался в микросервисахОтправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail11.12.2018, 23:52, "Alex Kovytin" <notifications@github.com>:@ujhgj requested changes on this pull request.



In README.md:
> +    "ping": "pong"
+}
+dbserver | SUCCESS => {
+    "changed": false, 
+    "ping": "pong"
+}
+
+ДЗ 9
+
+- Created ansible playbooks
+  - `reddit_app_one_play` 
+  - `reddit_app_multiple_plays`
+  - `app.yml`, `db.yml`, and `deploy.yml`  The playbooks imported in `site.yml` in predefined order to deploy Reddit application.
+  - `packer_db.yml` and `packer_app.yml` are the playbooks for packer images provisioning using ansible
+- Changed provisioning config in `packer/app.json` and `packer/db.json` to replace bash scripts with ansible playbooks
+- Created configuration for dynamic inventory using `gce.py`

однако, в ansible.cfg у вас зафиксирован статический inventory

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2018-12-11 21:12 UTC, Andreyovs commented on README.md
> +- Created configuration for dynamic inventory using `gce.py`
все верно не доделал

2018-12-13 16:03 UTC, Andreyovs commented on README.md
> +- Created configuration for dynamic inventory using `gce.py`
выложил динамический инвентори

2018-12-14 08:56 UTC, merged